DROP DATABASE IF EXISTS employee_tracker;
CREATE DATABASE employee_tracker;

USE employee_tracker;

CREATE TABLE department
 id INT NOT NULL AUTO_INCREMENT,
 title VARCHAR(30) NOT NULL,
 PRIMARY KEY

CREATE TABLE role
 id INT NOT NULL AUTO_INCREMENT,
 title VARCHAR(30) NOT NULL,
 salary DECIMAL NOT NULL,
 department_id INT,
 PRIMARY KEY
 

CREATE TABLE employee